const assert=require("assert");
const economy=require("./game-economy");
assert.equal(typeof economy.recordTransition,"function");
assert.equal(typeof economy.summary,"function");
assert.equal(economy.classify({raw_message:"Продление объявления"},{}, "Продлить"),"renewal");
assert.equal(economy.classify({raw_message:"Аукцион госномера"},{}, "Ставка"),"plate");
assert.equal(economy.classify({raw_message:"Предложение покупателя"},{}, "По рукам"),"sale");
assert.equal(economy.classify({raw_message:"Снять номер"},{}, "Снять номер"),"plate_removal");
assert.equal(economy.RENEWAL_COST,1500);
assert.equal(economy.PLATE_REMOVAL_COST,55000);
assert.equal(economy.PLATE_AUCTION_COMMISSION,0.10);
const p=economy.expectedSale(1000000,800000,0.10);
assert.equal(p.fee,100000);
assert.equal(p.profit,100000);
const vi=economy.vehicleInfo({vehicle:{name:"Audi A4"},plate:"У123АА 77"});
assert.equal(vi.key,"audi a4|у123аа 77");
console.log("GAME ECONOMY TESTS: PASS");
