package com.carflip.copilot

import android.content.Context
import org.json.JSONArray
import org.json.JSONObject

object CopilotState {
 private fun p(c:Context)=c.getSharedPreferences("copilot_state",Context.MODE_PRIVATE)
 private fun append(c:Context,key:String,o:JSONObject,max:Int=200){val a=JSONArray(p(c).getString(key,"[]"));a.put(o);while(a.length()>max)a.remove(0);p(c).edit().putString(key,a.toString()).apply()}
 fun addEvent(c:Context,text:String){append(c,"events",JSONObject().put("text",text).put("time",System.currentTimeMillis()),500)}
 fun roi(cost:Long,delta:Long):Double=if(cost<=0)0.0 else (delta-cost).toDouble()/cost.toDouble()*100.0
 fun events(c:Context):List<String>{val a=JSONArray(p(c).getString("events","[]"));return(0 until a.length()).mapNotNull{a.optJSONObject(it)?.optString("text")}.reversed()}
 fun addLedger(c:Context,type:String,amount:Long?,note:String){if(amount==null)return;append(c,"ledger",JSONObject().put("key",(type+"|"+amount+"|"+note).hashCode().toString()).put("type",type).put("amount",amount).put("note",note.take(500)).put("time",System.currentTimeMillis()))}
 fun ledger(c:Context):List<LedgerEvent>{val a=JSONArray(p(c).getString("ledger","[]"));return(0 until a.length()).map{val o=a.getJSONObject(it);LedgerEvent(o.optString("type"),o.optLong("amount"),o.optString("note"),o.optLong("time"))}.reversed()}
 fun recordPurchase(c:Context,v:VehicleSnapshot,amount:Long){val id=(v.plate.ifEmpty{v.name}).ifEmpty{"deal"}+"|"+System.currentTimeMillis();val o=JSONObject().put("id",id).put("name",v.name).put("plate",v.plate).put("buy",amount).put("fees",0L).put("opened",System.currentTimeMillis());append(c,"deals",o);addLedger(c,"ПОКУПКА",-amount,v.name.ifEmpty{"авто"})}
 fun recordSale(c:Context,v:VehicleSnapshot,amount:Long){val a=JSONArray(p(c).getString("deals","[]"));var idx=-1;for(i in a.length()-1 downTo 0){val o=a.optJSONObject(i)?:continue;if(!o.has("sell")&&((v.plate.isNotEmpty()&&o.optString("plate")==v.plate)||(v.plate.isEmpty()&&o.optString("name")==v.name))){idx=i;break}};var learnedProfit:Long?=null;if(idx>=0){val existing=a.getJSONObject(idx);val buy=if(existing.has("buy"))existing.optLong("buy") else 0L;val fees=existing.optLong("fees");learnedProfit=amount-buy-fees;a.put(idx,existing.put("sell",amount).put("closed",System.currentTimeMillis()))}else{a.put(JSONObject().put("id",(v.plate.ifEmpty{v.name})+"|"+System.currentTimeMillis()).put("name",v.name).put("plate",v.plate).put("sell",amount).put("fees",0L).put("opened",System.currentTimeMillis()).put("closed",System.currentTimeMillis()))};while(a.length()>200)a.remove(0);p(c).edit().putString("deals",a.toString()).apply();learnedProfit?.let{profit->val closed=a.optJSONObject(idx)?.optString("id")?:"";LearningMemory.recordAllActionOutcomes(c,v,amount,closed,v.plate);LearningMemory.learn(c,v,profit);calibrateActionRoi(c,v,profit);addEvent(c,"ОБУЧЕНИЕ • продажа "+amount+" ₽ • прибыль "+profit+" ₽ • действия откалиброваны • "+v.name)};addLedger(c,"ПРОДАЖА",amount,v.name.ifEmpty{"авто"})}
 fun calibrateActionRoi(c:Context,v:VehicleSnapshot,profit:Long){val a=JSONArray(p(c).getString("action_roi","[]"));val hist=JSONArray(p(c).getString("action_calibration","[]"));val dealId=deals(c).firstOrNull{it.closed==null&&((v.plate.isNotEmpty()&&it.plate==v.plate)||(v.plate.isEmpty()&&it.name==v.name))}?.id?:"";for(i in 0 until a.length()){val o=a.optJSONObject(i)?:continue;if(o.optString("deal_id").isNotEmpty()&&dealId.isNotEmpty()&&o.optString("deal_id")!=dealId)continue;if(o.optString("plate").isNotEmpty()&&v.plate.isNotEmpty()&&o.optString("plate")!=v.plate)continue;hist.put(JSONObject().put("action",ActionRoiEngine.normalize(o.optString("action"))).put("expected_delta",o.optLong("delta")).put("realized_profit",profit).put("deal_id",dealId).put("time",System.currentTimeMillis()))};while(hist.length()>500)hist.remove(0);p(c).edit().putString("action_calibration",hist.toString()).apply()}
 fun addFee(c:Context,amount:Long,note:String){val a=JSONArray(p(c).getString("deals","[]"));for(i in a.length()-1 downTo 0){val o=a.optJSONObject(i)?:continue;if(!o.has("closed")){o.put("fees",o.optLong("fees")+amount);break}};p(c).edit().putString("deals",a.toString()).apply();addLedger(c,"РАСХОД",-amount,note)}
}