package com.carflip.copilot

import android.content.Context
import org.json.JSONArray
import org.json.JSONObject
import kotlin.math.roundToInt

data class LearningStats(val samples:Int,val profitable:Int,val loss:Int,val avgProfit:Long,val accuracy:Int)

object LearningMemory {
 private const val PREF="copilot_learning"; private const val HISTORY="history"; private const val WEIGHTS="weights"
 private fun p(c:Context)=c.getSharedPreferences(PREF,Context.MODE_PRIVATE)
 private fun featureKey(v:VehicleSnapshot):String{val origin=v.origin.ifBlank{"UNKNOWN"};val hp=when{(v.hp?:0)>=600->"600+";(v.hp?:0)>=400->"400-599";(v.hp?:0)>=300->"300-399";else->"<300"};val price=when{(v.price?:Long.MAX_VALUE)<=1000000->"0-1m";(v.price?:Long.MAX_VALUE)<=2000000->"1-2m";(v.price?:Long.MAX_VALUE)<=2500000->"2-2.5m";else->"2.5m+"};return "$origin|$hp|$price"}
 fun learn(c:Context,v:VehicleSnapshot,profit:Long){val pref=p(c);val h=JSONArray(pref.getString(HISTORY,"[]"));h.put(JSONObject().put("feature",featureKey(v)).put("profit",profit).put("time",System.currentTimeMillis()));while(h.length()>500)h.remove(0);val w=JSONObject(pref.getString(WEIGHTS,"{}"));val key=featureKey(v);val reward=when{profit>0->1.0;profit<0->-1.0;else->0.0};w.put(key,(w.optDouble(key,0.0)*0.85+reward*0.15).coerceIn(-1.0,1.0));pref.edit().putString(HISTORY,h.toString()).putString(WEIGHTS,w.toString()).apply()}
 fun score(c:Context,v:VehicleSnapshot)=(JSONObject(p(c).getString(WEIGHTS,"{}")).optDouble(featureKey(v),0.0)*12.0).roundToInt()
 fun stats(c:Context):LearningStats{val a=JSONArray(p(c).getString(HISTORY,"[]"));var good=0;var loss=0;var sum=0L;for(i in 0 until a.length()){val n=a.optJSONObject(i)?.optLong("profit")?:0;sum+=n;if(n>0)good++ else if(n<0)loss++};val n=a.length();val accuracy=if(n==0)0 else (good.toDouble()/n*100).roundToInt();return LearningStats(n,good,loss,if(n==0)0 else sum/n,accuracy)}
 fun learnAction(c:Context,v:VehicleSnapshot,action:String,cost:Long,valueDelta:Long,beforeSale:Long?=null,dealId:String="",plate:String=""){val pref=p(c);val a=JSONArray(pref.getString("action_history","[]"));a.put(JSONObject().put("feature",featureKey(v)).put("action",ActionRoiEngine.normalize(action)).put("cost",cost).put("delta",valueDelta).put("roi",if(cost>0)(valueDelta-cost).toDouble()/cost*100.0 else 0.0).put("beforeSale",beforeSale?:JSONObject.NULL).put("deal_id",dealId).put("plate",plate).put("time",System.currentTimeMillis()));while(a.length()>500)a.remove(0);pref.edit().putString("action_history",a.toString()).apply()}
 fun estimatedSale(c:Context,v:VehicleSnapshot,fallback:Long?=null):Long?{val pref=c.getSharedPreferences("copilot_state",Context.MODE_PRIVATE);val a=try{JSONArray(pref.getString("buyer_offers","[]"))}catch(_:Exception){JSONArray()};val nums=mutableListOf<Long>();for(i in 0 until a.length()){val o=a.optJSONObject(i)?:continue;if(v.plate.isNotEmpty()&&o.optString("plate")!=v.plate)continue;val n=o.optLong("amount",0);if(n>0)nums+=n};return when{nums.isNotEmpty()->nums.average().toLong();fallback!=null->fallback;else->v.price}}
 private fun history(c:Context)=JSONArray(p(c).getString("action_history","[]"))
 fun actionSamples(c:Context,v:VehicleSnapshot,action:String)=run{val a=history(c);val n=ActionRoiEngine.normalize(action);(0 until a.length()).count{val o=a.optJSONObject(it);o!=null&&o.optString("feature")==featureKey(v)&&ActionRoiEngine.normalize(o.optString("action"))==n}}
 fun actionRoi(c:Context,v:VehicleSnapshot,action:String):Double?{val a=history(c);val n=ActionRoiEngine.normalize(action);val xs=(0 until a.length()).mapNotNull{val o=a.optJSONObject(it);if(o!=null&&o.optString("feature")==featureKey(v)&&ActionRoiEngine.normalize(o.optString("action"))==n)o.optDouble("roi")else null};return xs.takeIf{it.isNotEmpty()}?.average()}
 fun recordActionOutcome(c:Context,v:VehicleSnapshot,action:String,afterSale:Long,dealId:String="",plate:String=""){val a=history(c);val n=ActionRoiEngine.normalize(action);var changed=false;for(i in a.length()-1 downTo 0){val o=a.optJSONObject(i)?:continue;if(ActionRoiEngine.normalize(o.optString("action"))!=n||o.has("realizedDelta"))continue;if(dealId.isNotEmpty()&&o.optString("deal_id")!=dealId)continue;if(plate.isNotEmpty()&&o.optString("plate").isNotEmpty()&&o.optString("plate")!=plate)continue;val before=o.optLong("beforeSale",0);if(before<=0)continue;o.put("realizedDelta",afterSale-before).put("afterSale",afterSale).put("outcomeTime",System.currentTimeMillis());a.put(i,o);changed=true};if(changed)p(c).edit().putString("action_history",a.toString()).apply()}
 fun recordStateChange(c:Context,v:VehicleSnapshot,afterSale:Long,dealId:String="",plate:String="",action:String=""){val a=history(c);val n=ActionRoiEngine.normalize(action);val now=System.currentTimeMillis();var changed=false;for(i in a.length()-1 downTo 0){val o=a.optJSONObject(i)?:continue;if(o.has("stateAfter"))continue;if(action.isNotEmpty()&&ActionRoiEngine.normalize(o.optString("action"))!=n)continue;if(dealId.isNotEmpty()&&o.optString("deal_id")!=dealId)continue;if(plate.isNotEmpty()&&o.optString("plate").isNotEmpty()&&o.optString("plate")!=plate)continue;if(now-o.optLong("time",0)>10*60*1000L)continue;val before=o.optLong("beforeSale",0);if(before<=0||before==afterSale)continue;o.put("stateAfter",afterSale).put("stateDelta",afterSale-before).put("stateChangeTime",now);a.put(i,o);changed=true};if(changed)p(c).edit().putString("action_history",a.toString()).apply()}
 fun pendingAction(c:Context,v:VehicleSnapshot,action:String,dealId:String="",plate:String=""):Boolean{val a=history(c);val n=ActionRoiEngine.normalize(action);val now=System.currentTimeMillis();for(i in a.length()-1 downTo 0){val o=a.optJSONObject(i)?:continue;if(ActionRoiEngine.normalize(o.optString("action"))!=n||o.has("stateAfter"))continue;if(dealId.isNotEmpty()&&o.optString("deal_id")!=dealId)continue;if(plate.isNotEmpty()&&o.optString("plate").isNotEmpty()&&o.optString("plate")!=plate)continue;if(now-o.optLong("time",0)<=3*60*1000L&&o.optLong("beforeSale",0)>0)return true};return false}
 data class ActionLearningSummary(val action:String,val samples:Int,val realizedSamples:Int,val avgCost:Long?,val avgExpectedDelta:Long?,val avgStateDelta:Long?,val avgRealizedDelta:Long?,val realizedRoi:Double?,val expectedRoi:Double?,val confidence:Int)
 fun actionSummary(c:Context,v:VehicleSnapshot,action:String):ActionLearningSummary{val a=history(c);val n=ActionRoiEngine.normalize(action);val costs=mutableListOf<Long>();val expected=mutableListOf<Long>();val state=mutableListOf<Long>();val realized=mutableListOf<Long>();for(i in 0 until a.length()){val o=a.optJSONObject(i)?:continue;if(o.optString("feature")!=featureKey(v)||ActionRoiEngine.normalize(o.optString("action"))!=n)continue;o.optLong("cost",0).takeIf{it>0}?.let{costs+=it};o.optLong("delta",0).takeIf{it!=0L}?.let{expected+=it};if(o.has("stateDelta"))state+=o.optLong("stateDelta");if(o.has("realizedDelta"))realized+=o.optLong("realizedDelta")};val avg:(List<Long>)->Long?={if(it.isEmpty())null else it.average().toLong()};val cost=avg(costs);val exp=avg(expected);val st=avg(state);val real=avg(realized);val rr=if(cost!=null&&cost>0&&real!=null)(real-cost).toDouble()/cost*100 else null;val er=if(cost!=null&&cost>0&&exp!=null)(exp-cost).toDouble()/cost*100 else null;val count=costs.size;val conf=when{realized.size>=10->90;realized.size>=5->82;realized.size>=2->70;count>=5->58;count>=2->48;count>=1->38;else->20};return ActionLearningSummary(n,count,realized.size,cost,exp,st,real,rr,er,conf)}
 fun recordAllActionOutcomes(c:Context,v:VehicleSnapshot,afterSale:Long,dealId:String="",plate:String=""){val a=history(c);var changed=false;for(i in 0 until a.length()){val o=a.optJSONObject(i)?:continue;if(o.has("realizedDelta"))continue;if(dealId.isNotEmpty()&&o.optString("deal_id")!=dealId)continue;if(plate.isNotEmpty()&&o.optString("plate").isNotEmpty()&&o.optString("plate")!=plate)continue;val before=o.optLong("beforeSale",0);if(before<=0)continue;o.put("realizedDelta",afterSale-before).put("afterSale",afterSale).put("outcomeTime",System.currentTimeMillis());a.put(i,o);changed=true};if(changed)p(c).edit().putString("action_history",a.toString()).apply()}
 fun reset(c:Context){p(c).edit().clear().apply()}
}
