package com.carflip.copilot
import android.app.Activity
import android.app.AlertDialog
import android.content.Intent
import android.media.projection.MediaProjectionManager
import android.net.Uri
import android.provider.MediaStore
import android.os.*
import android.provider.Settings
import android.widget.*
import androidx.appcompat.app.AppCompatActivity

class MainActivity:AppCompatActivity(){
 private val captureCode=1001;private lateinit var status:TextView;private lateinit var vehicle:TextView;private lateinit var history:TextView;private lateinit var tabs:TextView;private lateinit var chatLog:TextView;private lateinit var chatInput:EditText;private val handler=Handler(Looper.getMainLooper())
 private val refreshTask=object:Runnable{override fun run(){refresh();handler.postDelayed(this,1000)}}
 override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(20,20,20,20)};val title=TextView(this).apply{text="🚗 Перекуп Copilot";textSize=28f};status=TextView(this).apply{textSize=16f;setPadding(0,14,0,12)};vehicle=TextView(this).apply{textSize=15f;setPadding(0,8,0,12)};tabs=TextView(this).apply{textSize=14f;setPadding(0,10,0,10)};history=TextView(this).apply{textSize=14f};val perm=Button(this).apply{text="Разрешить панель поверх Telegram";setOnClickListener{startActivity(Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,Uri.parse("package:"+packageName)))}};val start=Button(this).apply{text="Запустить мониторинг";setOnClickListener{requestCapture()}};val stop=Button(this).apply{text="Остановить мониторинг";setOnClickListener{stopService(Intent(this@MainActivity,ScreenMonitorService::class.java))}};val bridge=Button(this).apply{text="Подключить меня к Copilot";setOnClickListener{showBridgeDialog()}};root.addView(title);root.addView(status);root.addView(vehicle);root.addView(tabs);root.addView(perm);root.addView(start);root.addView(stop);root.addView(bridge);chatLog=TextView(this).apply{textSize=14f;setPadding(0,10,0,10)};chatInput=EditText(this).apply{hint="Напиши Copilot…";singleLine=true};val send=Button(this).apply{text="Отправить";setOnClickListener{sendChat()}};val attach=Button(this).apply{text="📎 Фото / видео / файл";setOnClickListener{pickAttachment()}};root.addView(attach);root.addView(TextView(this).apply{text="💬 Чат с Copilot";textSize=20f});root.addView(chatLog);root.addView(chatInput);root.addView(send);root.addView(history);loadChat();setContentView(ScrollView(this).apply{addView(root)})}
 private fun sendChat(){val msg=chatInput.text.toString().trim();if(msg.isBlank())return;ChatMemory.add(this,"user",msg);chatLog.append("Я: "+msg+"\n");chatInput.text.clear();startService(Intent(this,ScreenMonitorService::class.java).setAction("CHAT").putExtra("message",msg))}
 private fun loadChat(){chatLog.text=ChatMemory.read(this).takeLast(30).joinToString("\n"){if(it.first=="user")"Я: "+it.second else "Copilot: "+it.second}}
 private fun pickAttachment(){startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{type="*/*";putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);addCategory(Intent.CATEGORY_OPENABLE)},2002)}
 override fun onActivityResult(requestCode:Int,resultCode:Int,data:Intent?){super.onActivityResult(requestCode,resultCode,data);if(requestCode!=2002||resultCode!=Activity.RESULT_OK||data==null)return;val uris=mutableListOf<Uri>();data.data?.let{uris.add(it)};data.clipData?.let{for(i in 0 until it.itemCount)uris.add(it.getItemAt(i).uri)};uris.distinct().forEach{u->val name=getFileName(u);ChatMemory.add(this,"user","📎 "+name);if(::chatLog.isInitialized)chatLog.append("Я: 📎 "+name+"\n");startService(Intent(this,ScreenMonitorService::class.java).setAction("CHAT_FILE").putExtra("uri",u.toString()).putExtra("name",name))}}
 private fun getFileName(uri:Uri):String{var n="файл";contentResolver.query(uri,null,null,null,null)?.use{if(it.moveToFirst()){val i=it.getColumnIndex(MediaStore.MediaColumns.DISPLAY_NAME);if(i>=0)n=it.getString(i)}};return n}
 override fun onResume(){super.onResume();handler.post(refreshTask)};override fun onPause(){handler.removeCallbacks(refreshTask);super.onPause()}
 private fun fmt(v:Long)="%,d".format(v).replace(',',' ')
 private fun refresh(){if(::chatLog.isInitialized)chatLog.text=ChatMemory.read(this).takeLast(30).joinToString("\n"){if(it.first=="user")"Я: "+it.second else "Copilot: "+it.second}val b=CopilotState.balance(this);val v=CopilotState.snapshot(this);val g=CopilotState.garage(this);val d=CopilotState.decision(this);val ls=LearningMemory.stats(this);status.text="Решение: $d\nОбучение: ${ls.samples} сделок • ${ls.accuracy}% положительных\nБаланс: ${fmt(b)} ₽\nГараж: $g/3\nМониторинг: "+if(CopilotState.monitoring(this))"ВКЛ" else "ВЫКЛ";vehicle.text=if(v.name.isEmpty())"Последняя машина: пока нет распознавания" else "Последняя машина:\n${v.name}\n${TradeEconomics.summary(v)}\nМощность: ${v.hp?.let{"$it л.с."}?:"—"} • Происхождение: ${v.origin.ifEmpty{"—"}}\nКрашеных: ${v.paintedParts?:"—"}\nПробег: ${v.mileage?.let{fmt(it)+" км"}?:"—"} • Владельцев: ${v.owners?:"—"}\nНомер: ${v.plate.ifEmpty{"—"}}";val deals=CopilotState.deals(this).take(8).joinToString("\n"){x->val result=if(x.buy!=null&&x.sell!=null)"результат ${fmt(x.sell-x.buy-x.fees)} ₽" else "открыта";"• "+x.name.ifEmpty{"Авто"}+" "+x.plate+" • "+(x.buy?.let{"куплено "+fmt(it)+" ₽"}?:"")+" "+(x.sell?.let{"продано "+fmt(it)+" ₽"}?:"")+" • расходы "+fmt(x.fees)+" ₽ • $result"};tabs.text="Сделки:\n"+(deals.ifEmpty{"пока нет"})+"\n\nПоследние операции:\n"+CopilotState.ledger(this).take(10).joinToString("\n"){e->"• ${e.type}: ${fmt(e.amount?:0)} ₽ ${e.note}"};history.text="\nСобытия:\n"+CopilotState.events(this).take(12).joinToString("\n"){"• $it"}.ifEmpty{"пока пусто"}}
 private fun showBridgeDialog(){val p=getSharedPreferences("live_bridge",0);val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(20,0,20,0)};val url=EditText(this).apply{hint="wss://адрес-моста/ws";setText(p.getString("url","")?:"")};val token=EditText(this).apply{hint="Секретный ключ";setText(p.getString("token","")?:"")};box.addView(url);box.addView(token);AlertDialog.Builder(this).setTitle("Постоянный канал «телефон ↔ я»").setMessage("Адрес защищённого WebSocket-моста и ключ.").setView(box).setNegativeButton("Отмена",null).setPositiveButton("Сохранить"){_,_->LiveBridge(this){}.configure(url.text.toString(),token.text.toString());Toast.makeText(this,"Канал сохранён.",Toast.LENGTH_SHORT).show()}.show()}
 private fun requestCapture(){if(!Settings.canDrawOverlays(this)){startActivity(Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,Uri.parse("package:"+packageName)));return};val mgr=getSystemService(MEDIA_PROJECTION_SERVICE)as MediaProjectionManager;startActivityForResult(mgr.createScreenCaptureIntent(),captureCode)}
 override fun onActivityResult(requestCode:Int,resultCode:Int,data:Intent?){super.onActivityResult(requestCode,resultCode,data);if(requestCode==captureCode&&resultCode==Activity.RESULT_OK&&data!=null)startForegroundService(Intent(this,ScreenMonitorService::class.java).putExtra("resultCode",resultCode).putExtra("data",data))}
}